import type { Product } from "./types";

/**
 * Product photos are hotlinked from Wikimedia Commons via the stable
 * Special:FilePath redirect (so the URL never breaks even if the underlying
 * upload path changes), all free-to-use / openly licensed. Full credit +
 * license is shown in the site footer's "Photo credits" panel.
 *
 * IMPORTANT: every filename below was verified against its actual Commons
 * description (not just guessed from the name) after an earlier mistake —
 * "White_rabbit.JPG" turned out to be Jefferson Airplane album art, not a
 * rabbit. With 70 products and a real farm's real (limited) photo budget,
 * several closely-related cuts within a category intentionally share one
 * verified "butchered cut" photo — alt text stays honest about that (never
 * claims a generic cut photo shows one exact cut it doesn't).
 */
const img = (file: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${file}`;

function credit(file: string, license = "Wikimedia Commons") {
  return {
    title: file.replace(/_/g, " "),
    sourceUrl: `https://commons.wikimedia.org/wiki/File:${file}`,
    license,
  };
}

// ---- shared photo pool -----------------------------------------------
const PHOTO = {
  sheepLive: img("Sheep.jpg"),
  goatLive: img("Goat.jpg"),
  beefLive: img("Holstein_Cow_Grazing_01.jpg"),
  chickenLive: img("Free_range_chicken_flock.jpg"),
  duckLive: img("Duck.jpg"),
  rabbitLive: img("NewZealandWhiteRabbit.jpg"),

  lambChops: img("Lamb_chops,_2006.jpg"),
  goatChops: img("Goat_chops.jpg"),
  beefSteak: img("Hanger-steak-raw-MCB.jpg"),
  groundBeef: img("Ground_Beef.jpg"),
  rawChicken: img("Raw_chicken.jpg"),
  chickenWing: img("Plucked_chicken_wing.jpg"),
  duckMeat: img("Duck_meat.jpg"),
  genericCut: img("Cutting_of_meat.jpg"),

  chickenEggs: img("Carton_of_eggs.jpg"),
  duckEggs: img("Dirty_Cayuga_Duck_Eggs.jpg"),
  quailEggs: img("Quail_eggs.jpg"),
  gooseEggs: img("Raw_goose_eggs.jpg"),
};

const CREDIT = {
  sheepLive: credit("Sheep.jpg"),
  goatLive: credit("Goat.jpg"),
  beefLive: credit("Holstein_Cow_Grazing_01.jpg"),
  chickenLive: credit("Free_range_chicken_flock.jpg", "CC BY 2.0"),
  duckLive: credit("Duck.jpg"),
  rabbitLive: credit("NewZealandWhiteRabbit.jpg", "CC BY-SA 3.0"),

  lambChops: credit("Lamb_chops,_2006.jpg"),
  goatChops: credit("Goat_chops.jpg"),
  beefSteak: credit("Hanger-steak-raw-MCB.jpg"),
  groundBeef: credit("Ground_Beef.jpg"),
  rawChicken: credit("Raw_chicken.jpg"),
  chickenWing: credit("Plucked_chicken_wing.jpg"),
  duckMeat: credit("Duck_meat.jpg"),
  genericCut: credit("Cutting_of_meat.jpg", "CC BY-SA 4.0"),

  chickenEggs: credit("Carton_of_eggs.jpg", "CC BY 3.0"),
  duckEggs: credit("Dirty_Cayuga_Duck_Eggs.jpg"),
  quailEggs: credit("Quail_eggs.jpg"),
  gooseEggs: credit("Raw_goose_eggs.jpg"),
};

export const CATALOG: Product[] = [
  // =================================================================
  // SHEEP — 10 products
  // =================================================================
  {
    slug: "pasture-ewe",
    name: "Pasture-Raised Ewe",
    category: "sheep",
    unitType: "per_lb",
    cutType: "whole",
    pricePerLb: 4.99,
    unitNoun: "lb",
    portionOptions: [
      { label: "Quarter (~10 lb)", weightLb: 10 },
      { label: "Half (~20 lb)", weightLb: 20 },
      { label: "Whole (~40 lb)", weightLb: 40 },
    ],
    baseStock: 14,
    image: PHOTO.sheepLive,
    imageAlt: "A pasture-raised ewe standing in a green field",
    imageCredit: CREDIT.sheepLive,
    description: "Grass-fed ewe, dressed and cut to order. Mild, tender lamb/mutton raised on open pasture, no feedlots.",
    bullets: ["Grass-fed, pasture-raised — never a feedlot", "Cut into quarter, half, or whole portions", "Vacuum-sealed and flash-frozen for delivery"],
    marketNote: "$4.99/lb sits at the value end of the regional lamb & mutton market ($4.50–$7.50/lb direct-from-farm) versus $9–$14/lb for retail cuts.",
  },
  {
    slug: "lamb-rib-chops",
    name: "Lamb Rib Chops (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 10.99,
    unitNoun: "lb",
    avgWeightLb: 2,
    baseStock: 22,
    image: PHOTO.lambChops,
    imageAlt: "Butchered lamb rib chops, ready to cook",
    imageCredit: CREDIT.lambChops,
    description: "Frenched-style rib chops, butchered and portioned — grill or pan-sear in minutes.",
    bullets: ["Pre-cut, ready to cook tonight", "Sold in ~2 lb packs", "Same pasture-raised animals as our whole ewe"],
    marketNote: "$10.99/lb is in line with retail lamb rib chop pricing ($10–$16/lb).",
  },
  {
    slug: "lamb-loin-chops",
    name: "Lamb Loin Chops (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 12.99,
    unitNoun: "lb",
    avgWeightLb: 1.5,
    baseStock: 16,
    image: PHOTO.lambChops,
    imageAlt: "Butchered lamb loin chops — the same chop family as our rib chops, cut from the loin",
    imageCredit: CREDIT.lambChops,
    description: "The most tender chop on the animal — thicker-cut, mini-T-bone shape, best on a hot grill.",
    bullets: ["Our most tender chop cut", "Sold in ~1.5 lb packs", "Best cooked hot and fast"],
    marketNote: "$12.99/lb reflects loin chops' premium over rib chops in most butcher pricing.",
  },
  {
    slug: "lamb-leg",
    name: "Leg of Lamb (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 9.99,
    unitNoun: "lb",
    avgWeightLb: 4,
    baseStock: 10,
    image: PHOTO.genericCut,
    imageAlt: "Butchered lamb, ready to roast (leg of lamb)",
    imageCredit: CREDIT.genericCut,
    description: "Bone-in leg roast — the classic Sunday-dinner cut, feeds a table of 6-8.",
    bullets: ["Bone-in, ~4 lb roast", "Classic holiday centerpiece", "Same pasture-raised animals as our whole ewe"],
    marketNote: "$9.99/lb tracks retail bone-in leg-of-lamb pricing ($9–$13/lb).",
  },
  {
    slug: "lamb-shoulder",
    name: "Lamb Shoulder Roast (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.49,
    unitNoun: "lb",
    avgWeightLb: 3.5,
    baseStock: 12,
    image: PHOTO.genericCut,
    imageAlt: "Butchered lamb shoulder roast, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "A well-marbled, slow-braise cut — falls apart after a few hours low and slow.",
    bullets: ["Ideal for slow braising or stewing", "~3.5 lb roast", "Great value cut"],
    marketNote: "$8.49/lb is below typical shoulder-roast retail pricing ($9–$12/lb).",
  },
  {
    slug: "lamb-rack",
    name: "Rack of Lamb (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 16.99,
    unitNoun: "lb",
    avgWeightLb: 1.5,
    baseStock: 8,
    image: PHOTO.lambChops,
    imageAlt: "Butchered lamb — the rack is cut from the same rib section as our chops",
    imageCredit: CREDIT.lambChops,
    description: "A full Frenched rack, restaurant-style presentation — roast whole and slice tableside.",
    bullets: ["Frenched, presentation-ready", "~1.5 lb rack", "A special-occasion centerpiece"],
    marketNote: "$16.99/lb is well under restaurant/retail rack-of-lamb pricing ($20–$30/lb).",
  },
  {
    slug: "ground-lamb",
    name: "Ground Lamb (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.99,
    unitNoun: "lb",
    avgWeightLb: 1,
    baseStock: 24,
    image: PHOTO.genericCut,
    imageAlt: "Ground lamb, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Coarse-ground from trim, no fillers — kofta, burgers, or a rich bolognese.",
    bullets: ["1 lb packs", "No fillers or additives", "Great for burgers, kofta, or ragù"],
    marketNote: "$8.99/lb matches typical ground-lamb retail pricing ($8–$11/lb).",
  },
  {
    slug: "lamb-stew-meat",
    name: "Lamb Stew Meat (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.49,
    unitNoun: "lb",
    avgWeightLb: 1.5,
    baseStock: 18,
    image: PHOTO.genericCut,
    imageAlt: "Cubed lamb stew meat, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Pre-cubed shoulder and leg trim — straight into the stew pot, no knife work needed.",
    bullets: ["Pre-cubed, ready for the pot", "1.5 lb packs", "A budget-friendly cut"],
    marketNote: "$8.49/lb is competitive with retail lamb stew-meat pricing ($8–$10/lb).",
  },
  {
    slug: "lamb-shanks",
    name: "Lamb Shanks (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 9.49,
    unitNoun: "lb",
    avgWeightLb: 2,
    baseStock: 14,
    image: PHOTO.genericCut,
    imageAlt: "Butchered lamb shanks, ready to braise",
    imageCredit: CREDIT.genericCut,
    description: "Two bone-in shanks per pack — braise for hours until the meat falls off the bone.",
    bullets: ["2 shanks per pack (~2 lb)", "Braises to fall-off-the-bone in a few hours", "Bone-in, rich flavor"],
    marketNote: "$9.49/lb is in line with retail lamb shank pricing ($9–$13/lb).",
  },
  {
    slug: "lamb-riblets",
    name: "Lamb Riblets (Butchered)",
    category: "sheep",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 7.99,
    unitNoun: "lb",
    avgWeightLb: 2,
    baseStock: 15,
    image: PHOTO.genericCut,
    imageAlt: "Butchered lamb riblets, ready to grill or braise",
    imageCredit: CREDIT.genericCut,
    description: "The breast/rib-tip section — cheap, flavorful, great smoked or braised then grilled.",
    bullets: ["Our best-value lamb cut", "~2 lb pack", "Great smoked or braised then finished on the grill"],
    marketNote: "$7.99/lb undercuts most retail lamb rib pricing ($9–$12/lb).",
  },

  // =================================================================
  // GOAT — 10 products
  // =================================================================
  {
    slug: "hill-goat",
    name: "Hill-Raised Goat",
    category: "goat",
    unitType: "per_lb",
    cutType: "whole",
    pricePerLb: 5.99,
    unitNoun: "lb",
    portionOptions: [
      { label: "Quarter (~7 lb)", weightLb: 7 },
      { label: "Half (~14 lb)", weightLb: 14 },
      { label: "Whole (~28 lb)", weightLb: 28 },
    ],
    baseStock: 9,
    image: PHOTO.goatLive,
    imageAlt: "A goat standing on a hillside pasture",
    imageCredit: CREDIT.goatLive,
    description: "Free-range goat (chevon), lean and flavorful. A staple for curries, stews, and grilling.",
    bullets: ["Free-range, rotationally grazed", "Lean meat — lower fat than lamb or beef", "Cut into quarter, half, or whole portions"],
    marketNote: "$5.99/lb tracks current chevon averages, above lamb ($6–$9/lb direct-from-farm) due to demand outpacing US goat supply.",
  },
  {
    slug: "goat-chops",
    name: "Goat Chops (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 11.99,
    unitNoun: "lb",
    avgWeightLb: 2,
    baseStock: 16,
    image: PHOTO.goatChops,
    imageAlt: "Butchered goat chops, ready to cook",
    imageCredit: CREDIT.goatChops,
    description: "Ready-to-cook goat chops from the same hill-raised herd — great for curry or the grill.",
    bullets: ["Pre-cut, ready to cook tonight", "Sold in ~2 lb packs", "Same free-range herd as our whole goat"],
    marketNote: "$11.99/lb matches retail chevon chop pricing ($10–$14/lb).",
  },
  {
    slug: "goat-loin-chops",
    name: "Goat Loin Chops (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 13.49,
    unitNoun: "lb",
    avgWeightLb: 1.5,
    baseStock: 10,
    image: PHOTO.goatChops,
    imageAlt: "Butchered goat loin chops — same chop family, cut from the loin",
    imageCredit: CREDIT.goatChops,
    description: "The most tender goat chop, cut from the loin — quick-cook over high heat.",
    bullets: ["Our most tender goat cut", "~1.5 lb packs", "Best grilled hot and fast"],
    marketNote: "$13.49/lb reflects the usual premium of loin over rib/shoulder chops.",
  },
  {
    slug: "goat-leg",
    name: "Leg of Goat (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 10.99,
    unitNoun: "lb",
    avgWeightLb: 3.5,
    baseStock: 9,
    image: PHOTO.genericCut,
    imageAlt: "Butchered goat, ready to roast (leg of goat)",
    imageCredit: CREDIT.genericCut,
    description: "Bone-in leg roast, a centerpiece for a big dinner or roasted whole for a gathering.",
    bullets: ["Bone-in, ~3.5 lb roast", "A great roast or braise centerpiece", "Same hill-raised herd"],
    marketNote: "$10.99/lb tracks retail bone-in goat leg pricing ($10–$14/lb).",
  },
  {
    slug: "goat-shoulder",
    name: "Goat Shoulder (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 9.49,
    unitNoun: "lb",
    avgWeightLb: 3,
    baseStock: 11,
    image: PHOTO.genericCut,
    imageAlt: "Butchered goat shoulder, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "Well-marbled, built for slow cooking — birria, curry, or a low-and-slow roast.",
    bullets: ["Ideal for birria, curry, or slow roasting", "~3 lb roast", "Great value cut"],
    marketNote: "$9.49/lb is competitive with retail goat shoulder pricing ($9–$12/lb).",
  },
  {
    slug: "ground-goat",
    name: "Ground Goat (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 9.99,
    unitNoun: "lb",
    avgWeightLb: 1,
    baseStock: 20,
    image: PHOTO.genericCut,
    imageAlt: "Ground goat, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Lean coarse-ground goat, no fillers — kebabs, samosas, or a spiced ragù.",
    bullets: ["1 lb packs", "Lean — lower fat than ground beef or lamb", "Great for kebabs or samosas"],
    marketNote: "$9.99/lb matches specialty ground-goat retail pricing ($9–$12/lb).",
  },
  {
    slug: "goat-curry-stew-meat",
    name: "Goat Curry-Cut Stew Meat (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 9.49,
    unitNoun: "lb",
    avgWeightLb: 1.5,
    baseStock: 20,
    image: PHOTO.genericCut,
    imageAlt: "Cubed goat curry-cut stew meat, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Bone-in curry-cut pieces, cut small — the traditional cut for a proper goat curry.",
    bullets: ["Bone-in, traditional curry cut", "1.5 lb packs", "The cut most curry recipes call for"],
    marketNote: "$9.49/lb is in line with specialty curry-cut goat pricing.",
  },
  {
    slug: "goat-ribs",
    name: "Goat Ribs (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.49,
    unitNoun: "lb",
    avgWeightLb: 2,
    baseStock: 13,
    image: PHOTO.genericCut,
    imageAlt: "Butchered goat ribs, ready to grill or braise",
    imageCredit: CREDIT.genericCut,
    description: "Great smoked, grilled, or braised — a flavorful, budget-friendly cut.",
    bullets: ["~2 lb pack", "Great smoked or grilled", "Budget-friendly"],
    marketNote: "$8.49/lb undercuts most specialty goat rib pricing ($9–$12/lb).",
  },
  {
    slug: "goat-shank",
    name: "Goat Shanks (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 9.99,
    unitNoun: "lb",
    avgWeightLb: 2,
    baseStock: 12,
    image: PHOTO.genericCut,
    imageAlt: "Butchered goat shanks, ready to braise",
    imageCredit: CREDIT.genericCut,
    description: "Two bone-in shanks per pack — a long, slow braise rewards you with fall-apart meat.",
    bullets: ["2 shanks per pack (~2 lb)", "Braises to fall-off-the-bone", "Bone-in, rich flavor"],
    marketNote: "$9.99/lb is in line with specialty goat shank pricing ($9–$13/lb).",
  },
  {
    slug: "goat-liver",
    name: "Goat Liver (Butchered)",
    category: "goat",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 6.99,
    unitNoun: "lb",
    avgWeightLb: 1,
    baseStock: 9,
    image: PHOTO.genericCut,
    imageAlt: "Butchered goat liver, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "A nutrient-dense organ cut, popular pan-seared with onions or in pepper-soup style dishes.",
    bullets: ["1 lb packs", "Iron and vitamin-A rich", "A traditional, nose-to-tail cut"],
    marketNote: "$6.99/lb reflects typical organ-meat pricing — below muscle cuts.",
  },

  // =================================================================
  // BEEF — 10 products
  // =================================================================
  {
    slug: "pasture-beef",
    name: "Pasture-Raised Beef",
    category: "beef",
    unitType: "per_lb",
    cutType: "whole",
    pricePerLb: 6.49,
    unitNoun: "lb",
    portionOptions: [
      { label: "Quarter (~110 lb)", weightLb: 110 },
      { label: "Half (~220 lb)", weightLb: 220 },
      { label: "Whole (~440 lb)", weightLb: 440 },
    ],
    baseStock: 4,
    image: PHOTO.beefLive,
    imageAlt: "Pasture-raised cattle grazing in an open field",
    imageCredit: CREDIT.beefLive,
    description: "Grass-fed beef by the quarter, half, or whole animal, dry-aged and cut to your specification.",
    bullets: ["Grass-fed and grass-finished, rotationally grazed", "Dry-aged before cutting for better flavor", "Cut into quarter, half, or whole portions"],
    marketNote: "$6.49/lb is at the value end of whole/half-beef pricing ($5.50–$8/lb hanging weight) versus $9–$20/lb for retail cuts.",
  },
  {
    slug: "beef-ribeye-steaks",
    name: "Ribeye Steaks (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 13.99,
    unitNoun: "lb",
    avgWeightLb: 2,
    baseStock: 18,
    image: PHOTO.beefSteak,
    imageAlt: "Butchered raw beef ribeye steaks, ready to cook",
    imageCredit: CREDIT.beefSteak,
    description: "Well-marbled, individually portioned ribeyes from the same grass-fed herd.",
    bullets: ["Pre-cut, ready to cook tonight", "Sold in ~2 lb packs (2 steaks)", "Same grass-fed herd as our whole beef"],
    marketNote: "$13.99/lb undercuts typical grass-fed ribeye pricing ($16–$25/lb).",
  },
  {
    slug: "beef-sirloin-steaks",
    name: "Sirloin Steaks (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 11.99,
    unitNoun: "lb",
    avgWeightLb: 2,
    baseStock: 18,
    image: PHOTO.beefSteak,
    imageAlt: "Butchered raw beef sirloin steaks — same steak family as our ribeye, a leaner cut",
    imageCredit: CREDIT.beefSteak,
    description: "A leaner, budget-friendly steak — great for a weeknight grill or stir-fry strips.",
    bullets: ["Leaner than ribeye, great value", "~2 lb pack", "Good for grilling or stir-fry"],
    marketNote: "$11.99/lb is below typical grass-fed sirloin pricing ($14–$18/lb).",
  },
  {
    slug: "ground-beef",
    name: "Ground Beef (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 7.99,
    unitNoun: "lb",
    avgWeightLb: 1,
    baseStock: 30,
    image: PHOTO.groundBeef,
    imageAlt: "Ground beef, butchered and packed",
    imageCredit: CREDIT.groundBeef,
    description: "80/20 coarse-ground from grass-fed trim — burgers, tacos, or a weeknight bolognese.",
    bullets: ["1 lb packs, 80/20 blend", "No fillers or additives", "Our best-selling beef item"],
    marketNote: "$7.99/lb matches grass-fed ground beef retail pricing ($7–$10/lb).",
  },
  {
    slug: "beef-brisket",
    name: "Beef Brisket (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.99,
    unitNoun: "lb",
    avgWeightLb: 5,
    baseStock: 8,
    image: PHOTO.genericCut,
    imageAlt: "Butchered beef brisket, ready to smoke or braise",
    imageCredit: CREDIT.genericCut,
    description: "A full point-and-flat brisket — low and slow on the smoker for classic Texas-style barbecue.",
    bullets: ["~5 lb whole brisket", "Point and flat included", "Built for the smoker"],
    marketNote: "$8.99/lb is below typical grass-fed brisket pricing ($10–$14/lb).",
  },
  {
    slug: "beef-short-ribs",
    name: "Beef Short Ribs (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 9.99,
    unitNoun: "lb",
    avgWeightLb: 3,
    baseStock: 12,
    image: PHOTO.genericCut,
    imageAlt: "Butchered beef short ribs, ready to braise",
    imageCredit: CREDIT.genericCut,
    description: "Thick-cut, bone-in short ribs — braise until the meat falls off the bone.",
    bullets: ["~3 lb pack, bone-in", "Braises fall-off-the-bone in a few hours", "A restaurant-favorite cut"],
    marketNote: "$9.99/lb undercuts typical short-rib retail pricing ($11–$16/lb).",
  },
  {
    slug: "beef-chuck-roast",
    name: "Beef Chuck Roast (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.49,
    unitNoun: "lb",
    avgWeightLb: 3.5,
    baseStock: 14,
    image: PHOTO.genericCut,
    imageAlt: "Butchered beef chuck roast, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "The classic pot-roast cut — well-marbled and built for the slow cooker.",
    bullets: ["~3.5 lb roast", "Ideal for pot roast or slow cooker", "Great value cut"],
    marketNote: "$8.49/lb is competitive with retail chuck roast pricing ($8–$11/lb).",
  },
  {
    slug: "beef-stew-meat",
    name: "Beef Stew Meat (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.99,
    unitNoun: "lb",
    avgWeightLb: 1.5,
    baseStock: 20,
    image: PHOTO.genericCut,
    imageAlt: "Cubed beef stew meat, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Pre-cubed chuck trim — straight into the stew pot or pressure cooker.",
    bullets: ["Pre-cubed, ready for the pot", "1.5 lb packs", "A budget-friendly cut"],
    marketNote: "$8.99/lb matches typical beef stew-meat retail pricing.",
  },
  {
    slug: "beef-liver",
    name: "Beef Liver (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 5.99,
    unitNoun: "lb",
    avgWeightLb: 1.5,
    baseStock: 10,
    image: PHOTO.genericCut,
    imageAlt: "Butchered beef liver, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "Grass-fed liver, a nutrient-dense organ cut — classic with onions and bacon.",
    bullets: ["1.5 lb packs", "Iron, B12, and vitamin-A rich", "A traditional nose-to-tail cut"],
    marketNote: "$5.99/lb reflects typical organ-meat pricing — below muscle cuts.",
  },
  {
    slug: "beef-soup-bones",
    name: "Beef Soup & Marrow Bones (Butchered)",
    category: "beef",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 4.99,
    unitNoun: "lb",
    avgWeightLb: 3,
    baseStock: 16,
    image: PHOTO.genericCut,
    imageAlt: "Beef soup and marrow bones, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Marrow and knuckle bones for stock, bone broth, or roasting for marrow toast.",
    bullets: ["~3 lb pack", "Great for bone broth or stock", "A farm-to-table staple"],
    marketNote: "$4.99/lb is standard pricing for farm-direct soup bones.",
  },

  // =================================================================
  // CHICKEN — 10 products
  // =================================================================
  {
    slug: "farm-chicken",
    name: "Whole Farm Chicken",
    category: "chicken",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 13,
    unitNoun: "chicken",
    avgWeightLb: 4.2,
    baseStock: 26,
    image: PHOTO.chickenLive,
    imageAlt: "Free-range chickens foraging outdoors",
    imageCredit: CREDIT.chickenLive,
    description: "Whole free-range chicken, roughly 4 lb dressed. Pasture-raised, no antibiotics.",
    bullets: ["Free-range, foraged pasture diet", "No antibiotics, no added hormones", "Ready to roast — about 4 lb average"],
    marketNote: "$13/chicken (~$3.10/lb) is in line with free-range whole-chicken pricing, well under $5–$7/lb for organic/heritage breeds.",
  },
  {
    slug: "heritage-chicken",
    name: "Whole Heritage-Breed Chicken",
    category: "chicken",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 18,
    unitNoun: "chicken",
    avgWeightLb: 5.5,
    baseStock: 10,
    image: PHOTO.chickenLive,
    imageAlt: "Free-range chickens foraging outdoors — same flock, a slower-growing heritage breed",
    imageCredit: CREDIT.chickenLive,
    description: "A slower-growing heritage breed, more time on pasture, firmer texture and deeper flavor than a standard broiler.",
    bullets: ["Heritage breed, slower-growing", "~5.5 lb average — larger than our standard bird", "Firmer texture, deeper flavor"],
    marketNote: "$18/chicken reflects the real cost premium heritage breeds carry over standard broilers ($15–$25 typical retail).",
  },
  {
    slug: "chicken-thighs",
    name: "Chicken Thighs (Butchered)",
    category: "chicken",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 9,
    unitNoun: "pack",
    baseStock: 30,
    image: PHOTO.rawChicken,
    imageAlt: "Butchered raw chicken thighs, ready to cook",
    imageCredit: CREDIT.rawChicken,
    description: "Bone-in chicken thighs from the same free-range flock, butchered and packed — about 2 lb per pack.",
    bullets: ["Pre-cut, ready to cook tonight", "~2 lb pack, bone-in", "Same free-range flock as our whole chicken"],
    marketNote: "$9/pack (~$4.50/lb) tracks free-range chicken-thigh retail pricing.",
  },
  {
    slug: "chicken-breasts",
    name: "Chicken Breasts (Butchered)",
    category: "chicken",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 11,
    unitNoun: "pack",
    baseStock: 26,
    image: PHOTO.rawChicken,
    imageAlt: "Butchered raw chicken breasts, ready to cook",
    imageCredit: CREDIT.rawChicken,
    description: "Boneless, skinless breasts — 2 per pack, from the same free-range flock.",
    bullets: ["2 breasts per pack (~1.5 lb)", "Boneless, skinless", "Same free-range flock as our whole chicken"],
    marketNote: "$11/pack tracks free-range boneless chicken-breast pricing ($6–$8/lb).",
  },
  {
    slug: "chicken-wings",
    name: "Chicken Wings (Butchered)",
    category: "chicken",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 8,
    unitNoun: "pack",
    baseStock: 24,
    image: PHOTO.chickenWing,
    imageAlt: "A plucked raw chicken wing, ready to cook",
    imageCredit: CREDIT.chickenWing,
    description: "Whole wings, roughly 1.5 lb per pack — bake, fry, or smoke.",
    bullets: ["~1.5 lb pack", "Whole wings, not pre-cut into flats/drums", "Same free-range flock"],
    marketNote: "$8/pack is in line with free-range chicken-wing retail pricing.",
  },
  {
    slug: "chicken-drumsticks",
    name: "Chicken Drumsticks (Butchered)",
    category: "chicken",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 7,
    unitNoun: "pack",
    baseStock: 24,
    image: PHOTO.rawChicken,
    imageAlt: "Butchered raw chicken drumsticks, ready to cook",
    imageCredit: CREDIT.rawChicken,
    description: "A family favorite — about 1.5 lb per pack, bone-in.",
    bullets: ["~1.5 lb pack, bone-in", "A kid-favorite cut", "Same free-range flock"],
    marketNote: "$7/pack is competitive with free-range drumstick retail pricing.",
  },
  {
    slug: "ground-chicken",
    name: "Ground Chicken (Butchered)",
    category: "chicken",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 8,
    unitNoun: "pack",
    baseStock: 20,
    image: PHOTO.rawChicken,
    imageAlt: "Ground chicken, butchered and packed",
    imageCredit: CREDIT.rawChicken,
    description: "Coarse-ground from thigh and breast trim — a leaner alternative to ground beef.",
    bullets: ["~1 lb pack", "Leaner alternative to ground beef", "Great for burgers or meatballs"],
    marketNote: "$8/pack matches free-range ground-chicken retail pricing.",
  },
  {
    slug: "chicken-tenders",
    name: "Chicken Tenders (Butchered)",
    category: "chicken",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 10,
    unitNoun: "pack",
    baseStock: 18,
    image: PHOTO.rawChicken,
    imageAlt: "Butchered raw chicken tenders, ready to cook",
    imageCredit: CREDIT.rawChicken,
    description: "The tenderloin strip from the breast — quick-cooking, a kid-friendly favorite.",
    bullets: ["~1 lb pack", "Quick-cooking, kid-friendly", "Same free-range flock"],
    marketNote: "$10/pack is in line with free-range chicken-tender retail pricing.",
  },
  {
    slug: "chicken-livers",
    name: "Chicken Livers (Butchered)",
    category: "chicken",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 5,
    unitNoun: "pack",
    baseStock: 14,
    image: PHOTO.genericCut,
    imageAlt: "Butchered chicken livers, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "A nutrient-dense organ cut — pâté, or a quick sauté with onions.",
    bullets: ["~1 lb pack", "Iron and vitamin-A rich", "Great for pâté or a quick sauté"],
    marketNote: "$5/pack reflects typical organ-meat pricing.",
  },
  {
    slug: "chicken-feet",
    name: "Chicken Feet (Butchered)",
    category: "chicken",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 4,
    unitNoun: "pack",
    baseStock: 10,
    image: PHOTO.genericCut,
    imageAlt: "Cleaned chicken feet, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Cleaned and ready — the secret to a rich, gelatinous stock.",
    bullets: ["~1 lb pack, cleaned", "Makes exceptionally rich stock", "A nose-to-tail farm staple"],
    marketNote: "$4/pack is standard specialty-market pricing for chicken feet.",
  },

  // =================================================================
  // DUCK — 10 products
  // =================================================================
  {
    slug: "farm-duck",
    name: "Whole Farm Duck",
    category: "duck",
    unitType: "per_lb",
    cutType: "whole",
    pricePerLb: 7.99,
    unitNoun: "lb",
    avgWeightLb: 5,
    baseStock: 11,
    image: PHOTO.duckLive,
    imageAlt: "A duck standing outdoors",
    imageCredit: CREDIT.duckLive,
    description: "Whole pasture-raised duck, about 5 lb dressed. Rich, dark meat — a favorite for roasting.",
    bullets: ["Pasture-raised, pond access", "Whole bird, ~5 lb average dressed weight", "Great for roasting or confit"],
    marketNote: "$7.99/lb is set against specialty/farm-duck market rates ($7–$10/lb direct), above commodity supermarket duck ($3.50–$5/lb).",
  },
  {
    slug: "large-duck",
    name: "Large Whole Duck",
    category: "duck",
    unitType: "per_lb",
    cutType: "whole",
    pricePerLb: 8.49,
    unitNoun: "lb",
    avgWeightLb: 6.5,
    baseStock: 6,
    image: PHOTO.duckLive,
    imageAlt: "A duck standing outdoors — same pond-access flock, an older, larger bird",
    imageCredit: CREDIT.duckLive,
    description: "An older, larger bird from the same flock — more meat per duck for a bigger table.",
    bullets: ["~6.5 lb average dressed weight", "Same pasture-raised, pond-access flock", "Feeds a larger table"],
    marketNote: "$8.49/lb carries a modest premium over our standard duck for the larger size.",
  },
  {
    slug: "duck-breast",
    name: "Duck Breast (Butchered)",
    category: "duck",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 11,
    unitNoun: "pack",
    baseStock: 14,
    image: PHOTO.duckMeat,
    imageAlt: "Butchered duck meat, ready to cook",
    imageCredit: CREDIT.duckMeat,
    description: "Boneless duck breast, two to a pack, from the same pond-access flock as our whole duck.",
    bullets: ["2 breasts per pack, boneless", "Restaurant favorite — sear skin-side down", "Same pasture-raised flock"],
    marketNote: "$11/pack lines up with specialty duck-breast pricing ($10–$14 per 2-pack).",
  },
  {
    slug: "duck-legs",
    name: "Duck Legs (Butchered)",
    category: "duck",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 10,
    unitNoun: "pack",
    baseStock: 14,
    image: PHOTO.duckMeat,
    imageAlt: "Butchered duck meat — same flock, leg portions ready for confit",
    imageCredit: CREDIT.duckMeat,
    description: "Two duck legs per pack — the classic confit cut, also great braised.",
    bullets: ["2 legs per pack", "The classic confit cut", "Also excellent braised"],
    marketNote: "$10/pack tracks specialty duck-leg pricing.",
  },
  {
    slug: "ground-duck",
    name: "Ground Duck (Butchered)",
    category: "duck",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 9,
    unitNoun: "pack",
    baseStock: 12,
    image: PHOTO.duckMeat,
    imageAlt: "Butchered ground duck, packed",
    imageCredit: CREDIT.duckMeat,
    description: "Rich, coarse-ground duck — a standout burger or ragù base.",
    bullets: ["~1 lb pack", "Rich, distinctive flavor", "Great for burgers or ragù"],
    marketNote: "$9/pack is in line with specialty ground-duck pricing.",
  },
  {
    slug: "duck-wings",
    name: "Duck Wings (Butchered)",
    category: "duck",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 6,
    unitNoun: "pack",
    baseStock: 12,
    image: PHOTO.duckMeat,
    imageAlt: "Butchered duck meat — same flock, wing portions",
    imageCredit: CREDIT.duckMeat,
    description: "A smaller, richer take on wings — braise or confit for the best texture.",
    bullets: ["~1 lb pack", "Best braised or confit-style", "A budget-friendly duck cut"],
    marketNote: "$6/pack is standard specialty-market pricing for duck wings.",
  },
  {
    slug: "duck-fat",
    name: "Rendered Duck Fat",
    category: "duck",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 9,
    unitNoun: "jar",
    baseStock: 16,
    image: PHOTO.duckMeat,
    imageAlt: "Duck fat rendered from the same farm's ducks",
    imageCredit: CREDIT.duckMeat,
    description: "Rendered from our own ducks — roast potatoes in it once and you won't go back.",
    bullets: ["~16 oz jar", "Rendered from our own flock", "The secret to unbeatable roast potatoes"],
    marketNote: "$9/jar matches specialty rendered-duck-fat retail pricing ($8–$12).",
  },
  {
    slug: "duck-liver",
    name: "Duck Liver (Butchered)",
    category: "duck",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 7,
    unitNoun: "pack",
    baseStock: 8,
    image: PHOTO.genericCut,
    imageAlt: "Butchered duck liver, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "Rich organ meat — pan-sear or use as a base for a simple pâté.",
    bullets: ["~0.5 lb pack", "Rich, iron-dense organ meat", "Great for a quick pâté"],
    marketNote: "$7/pack reflects specialty organ-meat pricing.",
  },
  {
    slug: "duck-necks",
    name: "Duck Necks (Butchered)",
    category: "duck",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 5,
    unitNoun: "pack",
    baseStock: 10,
    image: PHOTO.genericCut,
    imageAlt: "Butchered duck necks, packed",
    imageCredit: CREDIT.genericCut,
    description: "Deeply flavorful stock-builders — simmer for a rich duck broth.",
    bullets: ["~1 lb pack", "Excellent for stock or broth", "A nose-to-tail staple"],
    marketNote: "$5/pack is standard pricing for farm-direct duck necks.",
  },
  {
    slug: "duck-bones",
    name: "Duck Carcass & Bones (for Stock)",
    category: "duck",
    unitType: "per_unit",
    cutType: "butchered",
    pricePerUnit: 4,
    unitNoun: "pack",
    baseStock: 12,
    image: PHOTO.genericCut,
    imageAlt: "Duck carcass and bones, packed for stock",
    imageCredit: CREDIT.genericCut,
    description: "Roast and simmer for a deeply savory duck stock — the base for pho or ramen.",
    bullets: ["~1.5 lb pack", "Great base for pho, ramen, or consommé", "A nose-to-tail farm staple"],
    marketNote: "$4/pack is standard farm-direct pricing for stock bones.",
  },

  // =================================================================
  // EGGS — 10 products
  // =================================================================
  {
    slug: "farm-eggs-dozen",
    name: "Farm-Fresh Eggs (Dozen)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 12,
    unitNoun: "dozen",
    baseStock: 40,
    image: PHOTO.chickenEggs,
    imageAlt: "An open carton of a dozen fresh brown chicken eggs",
    imageCredit: CREDIT.chickenEggs,
    description: "A dozen free-range chicken eggs, collected fresh and delivered within days, not weeks.",
    bullets: ["Collected within 72 hours of delivery", "Free-range hens, foraged diet", "Mixed medium-to-large sizing"],
    marketNote: "$12/dozen reflects current pasture-raised/free-range egg pricing.",
  },
  {
    slug: "chicken-eggs-18pack",
    name: "Chicken Eggs (18-Pack)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 16,
    unitNoun: "18-pack",
    baseStock: 24,
    image: PHOTO.chickenEggs,
    imageAlt: "A flat of free-range chicken eggs, same hens as our dozen carton",
    imageCredit: CREDIT.chickenEggs,
    description: "The bigger flat — same free-range hens, better price per egg for regular bakers.",
    bullets: ["18 eggs per flat", "Same free-range flock as our dozen", "Better per-egg price than a dozen"],
    marketNote: "$16/18-pack (~$0.89/egg) beats the per-egg cost of our dozen carton ($1.00/egg).",
  },
  {
    slug: "xl-chicken-eggs-dozen",
    name: "Extra Large Chicken Eggs (Dozen)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 13,
    unitNoun: "dozen",
    baseStock: 20,
    image: PHOTO.chickenEggs,
    imageAlt: "A carton of extra large free-range chicken eggs",
    imageCredit: CREDIT.chickenEggs,
    description: "Hand-sorted for size — from our most mature laying hens.",
    bullets: ["Hand-sorted extra-large sizing", "From our most mature hens", "Collected within 72 hours of delivery"],
    marketNote: "$13/dozen carries the usual small premium for size-sorted extra-large eggs.",
  },
  {
    slug: "jumbo-chicken-eggs-dozen",
    name: "Jumbo Chicken Eggs (Dozen)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 14,
    unitNoun: "dozen",
    baseStock: 14,
    image: PHOTO.chickenEggs,
    imageAlt: "A carton of jumbo free-range chicken eggs",
    imageCredit: CREDIT.chickenEggs,
    description: "Our largest chicken eggs — a limited weekly sort from the biggest layers.",
    bullets: ["Our largest available chicken eggs", "A limited weekly sort", "Collected within 72 hours of delivery"],
    marketNote: "$14/dozen reflects jumbo-egg market pricing (a step above extra-large).",
  },
  {
    slug: "white-chicken-eggs-dozen",
    name: "White Chicken Eggs (Dozen)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 12,
    unitNoun: "dozen",
    baseStock: 18,
    image: PHOTO.chickenEggs,
    imageAlt: "A carton of white free-range chicken eggs",
    imageCredit: CREDIT.chickenEggs,
    description: "From our white-egg-laying hens (Leghorns) — same free-range diet as our brown-egg flock.",
    bullets: ["From our Leghorn hens", "Same free-range, foraged diet", "Collected within 72 hours of delivery"],
    marketNote: "$12/dozen matches our standard carton — shell color doesn't change nutrition or price.",
  },
  {
    slug: "pullet-eggs-dozen",
    name: "Pullet Eggs (Dozen)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 9,
    unitNoun: "dozen",
    baseStock: 10,
    image: PHOTO.chickenEggs,
    imageAlt: "A carton of small pullet eggs from young hens",
    imageCredit: CREDIT.chickenEggs,
    description: "Small eggs from our young hens laying for the first time — sweet, rich yolks.",
    bullets: ["From young, first-time-laying hens", "Smaller size, extra-rich yolk ratio", "A seasonal, limited item"],
    marketNote: "$9/dozen is priced below standard eggs for the smaller size, in line with specialty pullet-egg pricing.",
  },
  {
    slug: "duck-eggs-dozen",
    name: "Duck Eggs (Dozen)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 14,
    unitNoun: "dozen",
    baseStock: 16,
    image: PHOTO.duckEggs,
    imageAlt: "A dozen dark-shelled Cayuga duck eggs",
    imageCredit: CREDIT.duckEggs,
    description: "Rich, large duck eggs from our Cayuga flock — a favorite for baking thanks to their bigger yolks.",
    bullets: ["Larger yolks than chicken eggs — great for baking", "Collected within 72 hours of delivery", "From the same pond-access ducks as our whole duck"],
    marketNote: "$14/dozen matches current specialty duck-egg pricing ($12–$16/dozen).",
  },
  {
    slug: "goose-eggs-6pack",
    name: "Goose Eggs (6-Pack)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 18,
    unitNoun: "6-pack",
    baseStock: 6,
    image: PHOTO.gooseEggs,
    imageAlt: "Raw goose eggs, six to a pack",
    imageCredit: CREDIT.gooseEggs,
    description: "Roughly triple the size of a chicken egg, rich and custardy — a seasonal specialty item.",
    bullets: ["~3x the size of a chicken egg", "Rich, custardy yolk", "A limited seasonal item"],
    marketNote: "$18/6-pack ($3/egg) is standard specialty pricing for goose eggs, reflecting low supply.",
  },
  {
    slug: "quail-eggs-18pack",
    name: "Quail Eggs (18-Pack)",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 9,
    unitNoun: "18-pack",
    baseStock: 20,
    image: PHOTO.quailEggs,
    imageAlt: "A pack of small speckled quail eggs",
    imageCredit: CREDIT.quailEggs,
    description: "Delicate, speckled quail eggs — a favorite garnish and appetizer ingredient, sold 18 to a pack.",
    bullets: ["18 eggs per pack (quail eggs run small)", "Popular for appetizers, ramen, and garnishes", "Collected within 72 hours of delivery"],
    marketNote: "$9 for 18 lines up with specialty quail-egg pricing (~$0.45–$0.60/egg).",
  },
  {
    slug: "egg-variety-bundle",
    name: "Farm Egg Variety Bundle",
    category: "eggs",
    unitType: "per_unit",
    cutType: "whole",
    pricePerUnit: 20,
    unitNoun: "bundle",
    baseStock: 12,
    image: PHOTO.chickenEggs,
    imageAlt: "A sampler carton mixing chicken, duck, and quail eggs",
    imageCredit: CREDIT.chickenEggs,
    description: "A sampler: half a dozen chicken eggs, half a dozen duck eggs, and a pack of quail eggs — taste the difference side by side.",
    bullets: ["6 chicken + 6 duck eggs + 12 quail eggs", "A great way to compare all three", "Our most popular gift item"],
    marketNote: "$20/bundle prices out below buying each component separately (~$23 combined).",
  },

  // =================================================================
  // RABBIT — 10 products
  // =================================================================
  {
    slug: "farm-rabbit",
    name: "Whole Farm Rabbit",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "whole",
    pricePerLb: 8.99,
    unitNoun: "lb",
    avgWeightLb: 3.5,
    baseStock: 8,
    image: PHOTO.rabbitLive,
    imageAlt: "A New Zealand White rabbit, a common meat-rabbit breed",
    imageCredit: CREDIT.rabbitLive,
    description: "Whole farm-raised rabbit, about 3.5 lb dressed. Lean, mild white meat.",
    bullets: ["Farm-raised meat rabbit breeds (New Zealand White)", "Lean, high-protein white meat", "Whole animal, ~3.5 lb average dressed weight"],
    marketNote: "$8.99/lb matches current specialty meat-rabbit pricing ($8–$10/lb direct-from-farm).",
  },
  {
    slug: "rabbit-cuts",
    name: "Rabbit Cuts (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 10.99,
    unitNoun: "lb",
    avgWeightLb: 1.5,
    baseStock: 10,
    image: PHOTO.genericCut,
    imageAlt: "Butchered rabbit cuts, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "Rabbit, butchered into serving pieces — ready for the braising pan, no whole-animal prep needed.",
    bullets: ["Pre-cut into serving pieces", "Sold in ~1.5 lb packs", "Same New Zealand White breed as our whole rabbit"],
    marketNote: "$10.99/lb reflects specialty butchered-rabbit retail pricing ($10–$13/lb).",
  },
  {
    slug: "rabbit-legs",
    name: "Rabbit Legs (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 11.99,
    unitNoun: "lb",
    avgWeightLb: 1,
    baseStock: 10,
    image: PHOTO.genericCut,
    imageAlt: "Butchered rabbit legs, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "Hind legs — the meatiest part of the rabbit, great braised or breaded and fried.",
    bullets: ["~1 lb pack", "The meatiest cut on the animal", "Great braised or breaded"],
    marketNote: "$11.99/lb tracks specialty rabbit-leg pricing.",
  },
  {
    slug: "rabbit-loin",
    name: "Rabbit Loin (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 14.99,
    unitNoun: "lb",
    avgWeightLb: 0.75,
    baseStock: 8,
    image: PHOTO.genericCut,
    imageAlt: "Butchered rabbit loin, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "The most tender cut on the rabbit — quick-cooking, often wrapped in bacon.",
    bullets: ["~0.75 lb pack", "The most tender rabbit cut", "Quick-cooking — don't overdo it"],
    marketNote: "$14.99/lb reflects the loin's usual premium over leg or stew cuts.",
  },
  {
    slug: "ground-rabbit",
    name: "Ground Rabbit (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 11.99,
    unitNoun: "lb",
    avgWeightLb: 1,
    baseStock: 10,
    image: PHOTO.genericCut,
    imageAlt: "Ground rabbit, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Very lean, mild ground meat — a lighter alternative to ground pork or beef.",
    bullets: ["1 lb packs", "Very lean, mild flavor", "A lighter alternative to ground pork or beef"],
    marketNote: "$11.99/lb matches specialty ground-rabbit retail pricing.",
  },
  {
    slug: "rabbit-stew-meat",
    name: "Rabbit Stew Meat (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 10.99,
    unitNoun: "lb",
    avgWeightLb: 1.25,
    baseStock: 10,
    image: PHOTO.genericCut,
    imageAlt: "Cubed rabbit stew meat, butchered and packed",
    imageCredit: CREDIT.genericCut,
    description: "Pre-cubed rabbit — classic in a mustard-cream braise or hearty stew.",
    bullets: ["Pre-cubed, ready for the pot", "1.25 lb packs", "Classic in a mustard-cream braise"],
    marketNote: "$10.99/lb is competitive with specialty rabbit stew-meat pricing.",
  },
  {
    slug: "rabbit-liver",
    name: "Rabbit Liver (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.99,
    unitNoun: "lb",
    avgWeightLb: 0.5,
    baseStock: 6,
    image: PHOTO.genericCut,
    imageAlt: "Butchered rabbit liver, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "A delicate organ cut, popular pan-seared or in a simple pâté.",
    bullets: ["~0.5 lb pack", "Delicate flavor, mild organ meat", "Great pan-seared or in pâté"],
    marketNote: "$8.99/lb reflects specialty organ-meat pricing.",
  },
  {
    slug: "rabbit-kidneys",
    name: "Rabbit Kidneys (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 8.99,
    unitNoun: "lb",
    avgWeightLb: 0.5,
    baseStock: 5,
    image: PHOTO.genericCut,
    imageAlt: "Butchered rabbit kidneys, ready to cook",
    imageCredit: CREDIT.genericCut,
    description: "A traditional nose-to-tail cut — sautéed quickly with mustard and herbs.",
    bullets: ["~0.5 lb pack", "A traditional nose-to-tail cut", "Best cooked quickly over high heat"],
    marketNote: "$8.99/lb matches specialty organ-meat pricing.",
  },
  {
    slug: "rabbit-saddle",
    name: "Rabbit Saddle (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 15.99,
    unitNoun: "lb",
    avgWeightLb: 1,
    baseStock: 6,
    image: PHOTO.genericCut,
    imageAlt: "Butchered rabbit saddle, a premium cut",
    imageCredit: CREDIT.genericCut,
    description: "The prized mid-section cut, bone-in — the cut you'll see on a fine-dining menu.",
    bullets: ["~1 lb pack, bone-in", "The most prized rabbit cut", "A restaurant-menu favorite"],
    marketNote: "$15.99/lb reflects the saddle's premium status among rabbit cuts.",
  },
  {
    slug: "rabbit-sausage",
    name: "Rabbit Sausage (Butchered)",
    category: "rabbit",
    unitType: "per_lb",
    cutType: "butchered",
    pricePerLb: 12.99,
    unitNoun: "lb",
    avgWeightLb: 1,
    baseStock: 12,
    image: PHOTO.genericCut,
    imageAlt: "Rabbit sausage links, made in-house",
    imageCredit: CREDIT.genericCut,
    description: "House-made links blending rabbit with herbs — a value-added way to try rabbit for the first time.",
    bullets: ["~1 lb pack (4-5 links)", "House-made, herb-blended", "A great first taste of rabbit"],
    marketNote: "$12.99/lb reflects the value-added cost of house-made sausage over raw cuts.",
  },
];

export function getProduct(slug: string): Product | undefined {
  return CATALOG.find((p) => p.slug === slug);
}

export const CATEGORY_LABELS: Record<Product["category"], string> = {
  sheep: "Sheep",
  goat: "Goat",
  beef: "Beef",
  chicken: "Chicken",
  eggs: "Eggs",
  duck: "Duck",
  rabbit: "Rabbit",
};

/**
 * Genuine "goes well together" pairings by category, used to drive
 * Frequently Bought Together — e.g. chicken pairs with eggs, not sheep.
 * Every category always pairs with itself first (e.g. whole + butchered
 * cuts of the same animal).
 */
export const CATEGORY_PAIRINGS: Record<Product["category"], Product["category"][]> = {
  chicken: ["chicken", "eggs", "duck"],
  eggs: ["eggs", "chicken", "duck"],
  duck: ["duck", "eggs", "chicken"],
  sheep: ["sheep", "goat", "beef"],
  goat: ["goat", "sheep", "beef"],
  beef: ["beef", "sheep", "goat"],
  rabbit: ["rabbit", "chicken", "duck"],
};
